### ISSUE TITLE
JSDoc の書き方

### ISSUE THREAD

**Issue by futoshi-takahashi** [lincwell/frontend-coding-guideline#16]
JSDocの利用目的が仕様書の自動作成ではなく、vscodeでホバーした時の注釈のため、基本的に本文のみで運用するのが適切だと思います。

# 例外的に使用するアノテーション

- @see
参照先のURL等をリンクする場合は@seeを用いるのがよさそうです。
```
/**
 * @see https://ics.media/entry/6789/
 */
```

- @deprecated
使用して欲しくない場合に記載するとvscodeの場合、該当するアイテムに取り消し線が引かれるため、便利です。
```
/** @deprecated 関数で運用すると()の記載が必要なため、定数のMEDIA_QUERY_PCを用意した*/
export const mediaQueryPc = (style?: StyleType) => mediaQueryMin(threshold[PC], style)
export const MEDIA_QUERY_PC = mediaQueryMin(threshold[PC])()
```
# 付与対象毎の注釈の指針

## Reactのコンポーネント
　使用するページ　　
　表示方法

```
/**
 * 数値の入力に使用
 * 予約詳細 > 決済 > 一部のポイントを使用する
 */
export const NumberBoxInput = ({ textBox, props }: CustomInputProps) => (
```

## 関数
　作成意図や期待動作

### 必要な場合に付与するアノテーション
-  @param
引数に対して特別な注釈する場合、@paramを使用(複数可)
※ 引数の変数名などで値の詳細がわかりにくい場合など
```
/**
 * 一定時間、処理を遅延させます。
 * @param {number} time 待機時間（単位：ミリ秒）
 * @param {number} count 待機回数（単位：回）
 */
const waitTime =(time:number,count:number) => ...
```
 -  @return
戻り値に対して特別な注釈する場合、@returnを使用
※ 関数名などで戻り値の詳細がわかりにくい場合など
```
/**
 * @return {number} 経過時間（単位：ミリ秒）
 */
const getTime =() => ... 
```

## 変数・定数
　名称から利用目的が明確出ない場合の注釈
```
/**
 * halfModalをpageModalの上に表示させるために用途で作成したhtmlのID
 * src/launch/main_contents.tsxでIDを割り当て
 */
export const HalfModalHighPriorityID = 'half-modal-id-high-priority'
```

**Comment by to-na** [comment]
@futoshi-takahashi ありがとうございます！　個人的には、export する関数には常に `@param`, `@return` をつけるようにしたほうが良いかなと思います。関数のわかりやすさはある程度主観が入ってしまうため、実装時・コードレビュー時に必ずつけるというルールにしたほうが運用しやすそうなため

**Comment by mpayu2** [comment]
@futoshi-takahashi 
とてもわかりやすいドキュメントを作成頂き、ありがとうございます！🙌

>個人的には、export する関数には常に @param, @return をつけるようにしたほうが良いかなと思います。関数のわかりやすさはある程度主観が入ってしまうため、実装時・コードレビュー時に必ずつけるというルールにしたほうが運用しやすそうなため

上記、私も賛成です！

あと、細かい点で2点、コメントです！

1. 「定数・変数」の箇所の「名称から利用目的が明確出ない場合の注釈」のところ、「名称から利用目的が明確でない場合の注釈」（明確でない）の方がナチュラルかと思いました
2. 注釈のところ、下記のようにフォーマットしても良さそうと思いました（こちらは余裕があればなので、そのままで良さそうです！）

```
/**
 * - halfModalをpageModalの上に表示させるために用途で作成したhtmlのID
 * - `src/launch/main_contents.tsx`でIDを割り当て
 */
```

**Comment by futoshi-takahashi** [comment]
コメントありがとうございます。

以下のような修正とします。

# JSDoc
## 例外的に使用するアノテーション

- @see
参照先のURL等をリンクする場合は@seeを用いるのがよさそうです。
```
/**
 * @see https://ics.media/entry/6789/
 */
```

- @deprecated
使用して欲しくない場合に記載するとvscodeの場合、該当するアイテムに取り消し線が引かれるため、便利です。
```
/** @deprecated 関数で運用すると()の記載が必要なため、定数のMEDIA_QUERY_PCを用意した*/
export const mediaQueryPc = (style?: StyleType) => mediaQueryMin(threshold[PC], style)
export const MEDIA_QUERY_PC = mediaQueryMin(threshold[PC])()
```
## 付与対象毎の注釈の指針

### Reactのコンポーネント
　使用するページ　　
　表示方法

```
/**
 * 数値の入力に使用
 * 予約詳細 > 決済 > 一部のポイントを使用する
 */
export const NumberBoxInput = ({ textBox, props }: CustomInputProps) => (
```

### 関数
　作成意図や期待動作

#### export する場合、もしくは、必要な場合に付与するアノテーション
-  @param
※ 複数可
```
/**
 * 一定時間、処理を遅延させます。
 * @param {number} time 待機時間（単位：ミリ秒）
 * @param {number} count 待機回数（単位：回）
 */
const waitTime =(time:number,count:number) => ...
```
 -  @return
```
/**
 * @return {number} 経過時間（単位：ミリ秒）
 */
const getTime =() => ... 
```

### 変数・定数
　利用目的
　※ 名称から利用目的が明確でない場合に付与
```
/**
 * halfModalをpageModalの上に表示させるために用途で作成したhtmlのID
 * src/launch/main_contents.tsxでIDを割り当て
 */
export const HalfModalHighPriorityID = 'half-modal-id-high-priority'
```

**Comment by to-na** [comment]
@futoshi-takahashi 
追加ですみません、React コンポーネントの場合、「表示方法」は一例であるように書いてほしいです。再利用性が無いように思う可能性があるため。
具体的には、
`例: 予約詳細 > 決済 > 一部のポイントを使用する`
のようにしたほうが良いと考えています。

**Comment by futoshi-takahashi** [comment]
>React コンポーネントの場合、「表示方法」は一例であるように書いてほしいです。再利用性が無いように思う可能性があるため。

上記、かしこまりました。
[コード規約のPR](https://github.com/lincwell/frontend-coding-guideline/pull/17)を修正しました。

**Comment by to-na** [comment]
https://github.com/lincwell/frontend-coding-guideline/pull/17
