### ISSUE TITLE
【追加要望】CSS

### ISSUE THREAD

**Issue by diverstage** [lincwell/frontend-coding-guideline#7]
## CSS

- idセレクタ、タイプセレクタへのスタイル指定はしない（classセレクタのみ）
  - スタイルがタイプに依存することで、保守性が下がるため
  - ulやolに対してのliや、dlに対してのdtやddなどは対象外（構造としてタイプが決まってしまっていて変更になる可能性が少ないため）

```
// Good
.header {
  / * some style */
}

// Bad
header {
  / * some style */
}

// Bad
#header {
  / * some style */
}
```

- 子セレクタ、子孫セレクタは極力使わない
  - ブラウザにとっては負荷が高まるため
  - 影響範囲が分かりづらくなるため

```
// Good
.hoge-fuga {
  / * some style */
}

// Bad
.hoge .fuga {
  / * some style */
}
```

- 値として「0」の場合は単位を指定しない

```
// Good
.example {
 margin-top: 0;
}

// Bad
.example {
 margin-top: 0px;
}
```

- !important を使用しない

**Comment by to-na** [comment]
内容良いと思います。
文言もこのままで問題なさそうなので、`html-and-css/README.md` に追記する形でPR作ってOKです。

**Comment by diverstage** [comment]
@to-na 
```
Git: Permission to lincwell/frontend-coding-guideline.git denied to diverstage.
```
プッシュしようとするとこの様に出るので、閲覧はできるのですが、プッシュする権限は私にはない感じですかね🤔

**Comment by to-na** [comment]
Push しようとしているのは main ブランチですか？
通常 main に直接 Push できないようにしているので、その場合はその影響だと思われます。

**Comment by diverstage** [comment]
@to-na 
> Push しようとしているのは main ブランチですか？

いえ、さすがにmainに直接Pushはしてなくて feature/add_css_guide_20220207 ってブランチ切ってプッシュしてプルリクを作ろうとしてましたね。
<img width="500" alt="image" src="https://user-images.githubusercontent.com/51035860/152895235-c6113649-7c18-44da-b782-f998a417f898.png">

Clone は普通にできたので何でなんかなと思いまして🤔

私の方の設定をもう一度確認してみたいと思います🙇‍♂️

**Comment by to-na** [comment]
@diverstage 
こちら direct access の権限がなかったためだと思われます 🙇 
invite しようとしましたが seats が少ないので自分の方で追記しておきます！

**Comment by diverstage** [comment]
> @diverstage こちら direct access の権限がなかったためだと思われます 🙇 invite しようとしましたが seats が少ないので自分の方で追記しておきます！

@to-na 
ありがとうございます！よろしくお願いいたします🙇‍♂️

**Comment by to-na** [comment]
https://github.com/lincwell/frontend-coding-guideline/pull/8 で対応しました 🙆‍♂️
