### ISSUE TITLE
TypeScript のファイル命名について

### ISSUE THREAD

**Issue by to-na** [lincwell/frontend-coding-guideline#9]
コンポーネントのファイル命名は `UpperCamelCase.tsx` でいいと思うんですが、ライブラリ系はインポート時に `import { foo } from "package-name/kebab-case"` という書き方が主流な認識で、故に `kebab-case.ts` の方が自然な気がしてきたんですが、どうでしょうか？

**Comment by ssshun** [comment]
ざっといくつかGitHubのプロジェクト見てきましたが、ケバブケースを主流としていろんな流派がありそうですね。
ケバブケース：Vue, Next.js(多分多数派)
キャメルケース：React, Apollo Client
スネークケース：Node.js, Angular

慣れとか使いやすさで選んで良いかなと思いますがどうでしょう？

**Comment by ssshun** [comment]
React用のパッケージでもいろんな流派がありそう

**Comment by ssshun** [comment]
あくまで個人的にですが、
キャメルケース > ケバブケース > スネークケース の順で良いかなと思いました。

・ケバブケースはコピーにちょっと手間
・スネークケースはフロントエンドプロジェクトで見慣れなさすぎる(使いにくさはないと思う)

**Comment by to-na** [comment]
色々 repo 見てますが結構バラバラですね
決めの問題っぽいので、 `UpperCamelCase.tsx` + `lowerCamelCase.ts` にしますか

**Comment by to-na** [comment]
今のルールだと↑と一緒なので、現状維持でいきます
